name: dina_korean_real
description: "A new Flutter project."
publish_to: 'none' # pub.dev ga publish qilinmasin

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  iconly: ^1.0.1
  get_it: ^8.0.3
  pdf: ^3.11.3
  percent_indicator: ^4.2.4
  go_router: ^14.8.0
  easy_localization: ^3.0.7+1
  permission_handler: ^11.3.1
  flutter_pdfview: ^1.4.0
  logger: ^2.5.0
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  flutter_bloc: ^9.1.0
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
  intl_phone_field: ^3.2.0
  image_picker: ^1.1.2
  local_auth: ^2.3.0
  flutter_spinkit: ^5.2.1
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  equatable: ^2.0.7
  loading_indicator: ^3.1.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.1.0
  flutter_switch: ^0.3.2
  flutter_riverpod: ^2.6.1
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  get_storage: ^2.1.1
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.8.0
  video_player: ^2.9.5
  audioplayers: ^6.4.0
  expansion_tile_card: ^3.0.0
  mockito: ^5.4.6
  flutter_inappwebview: ^6.1.5
  webview_flutter: ^4.13.0
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/sign/
    - assets/home/
    - assets/profile/
    - assets/online_lessons/
